name: Metrics
on:
  # Schedule updates (once a day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run it manually from the Actions tab
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: TrisTheKitten
          template: classic
          base: ""
          config_timezone: Asia/Bangkok
          
          # The 3D Calendar options
          filename: metrics.plugin.isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
