name: Metrics
on:
  # Schedule updates (once a day)
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Generate the 3D Calendar
      - name: 3D Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TrisTheKitten
          template: classic
          base: ""
          config_timezone: Asia/Bangkok
          filename: metrics.plugin.isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # Step 2: Generate Indepth & Recent Languages
      - name: Indepth & Recent Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TrisTheKitten
          template: classic
          base: ""
          config_timezone: Asia/Bangkok
          filename: metrics.plugin.languages.svg
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
